from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "data" / "ground_truth"
OUTPUT_PATH = OUTPUT_DIR / "ground_truth_competition_rules_v1_228.jsonl"


def case(
    key: str,
    game: str,
    intent: str,
    source_id: str,
    expected_keywords: list[str],
    questions: list[str],
    *,
    answer_type: str = "fact",
    difficulty: str = "medium",
) -> dict[str, Any]:
    return {
        "key": key,
        "game": game,
        "intent": intent,
        "source_id": source_id,
        "expected_keywords": expected_keywords,
        "questions": questions,
        "answer_type": answer_type,
        "difficulty": difficulty,
    }


CASES = [
    case(
        "cs2_team_size",
        "Counter-Strike 2",
        "team_size",
        "competition_rules_cs2_psu_phuket_2026",
        ["CS2", "ผู้เล่น 5 คน"],
        [
            "CS2 แข่งทีมละกี่คน",
            "Counter-Strike 2 ทีมละกี่คนตามกติกา",
            "กติกา CS2 ต้องมีผู้เล่นกี่คนต่อทีม",
            "CS2 สมาชิกทีมต้องมีกี่คน",
            "CS2 ลงแข่งพร้อมกันกี่คน",
            "CS2 roster ผู้เล่นหลักมีกี่คน",
            "รายการ PSU Phuket CS2 2026 ทีมละกี่คน",
            "CS2 ต้องส่งผู้เล่นกี่คนในทีม",
            "CS2 แข่งแบบทีม 5 คนใช่ไหม",
            "Counter Strike 2 ในรายการนี้ผู้เล่นต่อทีมกี่คน",
            "CS2 ถ้าถามเรื่องจำนวนคนในทีมตอบว่าอะไร",
            "CS2 กติกาองค์ประกอบทีมกำหนดไว้กี่คน",
        ],
    ),
    case(
        "cs2_map_pool",
        "Counter-Strike 2",
        "map_pool",
        "competition_rules_cs2_psu_phuket_2026",
        ["Ancient", "Anubis", "Dust 2", "Train"],
        [
            "CS2 ใช้ map อะไรบ้าง",
            "CS2 map pool มีอะไรบ้าง",
            "CS2 แผนที่ที่ใช้แข่งมีอะไรบ้าง",
            "กติกา CS2 ระบุแผนที่อะไรบ้าง",
            "PSU Phuket CS2 2026 ใช้แผนที่ไหน",
            "CS2 มี Ancient กับ Anubis ใน map pool ไหม",
            "CS2 รายการนี้ใช้ Dust 2 หรือ Train ไหม",
            "ขอรายชื่อ map ที่ใช้แข่ง CS2",
            "Counter-Strike 2 map pool ในกติกาคืออะไร",
            "CS2 แข่งบนแผนที่อะไรได้บ้าง",
            "CS2 ban map จาก pool ไหน",
            "CS2 แผนที่ทั้งหมดตามกติกามีอะไร",
        ],
    ),
    case(
        "cs2_format",
        "Counter-Strike 2",
        "format",
        "competition_rules_cs2_psu_phuket_2026",
        ["Single Elimination", "BO3"],
        [
            "CS2 แข่งรูปแบบอะไร",
            "CS2 เป็น Single Elimination ไหม",
            "CS2 รอบรองกับรอบชิงเป็น BO อะไร",
            "กติกา CS2 format การแข่งขันเป็นยังไง",
            "PSU Phuket CS2 2026 ใช้ระบบแข่งแบบไหน",
            "CS2 รอบชิงใช้ BO3 ใช่ไหม",
            "CS2 รอบรองชนะเลิศแข่งกี่เกม",
            "Counter-Strike 2 tournament format คืออะไร",
            "CS2 แข่งแพ้คัดออกหรือเปล่า",
            "CS2 รูปแบบทัวร์นาเมนต์ในเอกสารคืออะไร",
            "CS2 รอบสำคัญเป็น Best of 3 ไหม",
            "CS2 กติกาบอกว่า single elimination หรือไม่",
        ],
    ),
    case(
        "cs2_pause",
        "Counter-Strike 2",
        "pause",
        "competition_rules_cs2_psu_phuket_2026",
        ["Technical Pause", "2 ครั้ง", "10 นาที", "Tactical Timeout", "4 ครั้ง", "30 วินาที"],
        [
            "CS2 technical pause ได้กี่ครั้ง",
            "CS2 tactical timeout ได้กี่ครั้ง",
            "CS2 pause ได้กี่ครั้งตามกติกา",
            "CS2 ขอหยุดเกม technical ได้กี่ครั้งและกี่นาที",
            "กติกา CS2 tactical timeout ครั้งละกี่วินาที",
            "CS2 Technical Pause รวมได้ไม่เกินกี่นาที",
            "CS2 เวลานอก tactical timeout ได้ทีมละกี่ครั้ง",
            "CS2 ถ้าเครื่องมีปัญหาขอ pause ได้เท่าไหร่",
            "Counter-Strike 2 pause policy เป็นยังไง",
            "CS2 technical กับ tactical timeout ต่างกันยังไงในกติกา",
            "CS2 ขอ Tactical Timeout 4 ครั้งใช่ไหม",
            "CS2 หยุดเกมได้กี่ครั้งและใช้เวลากี่วินาที",
        ],
    ),
    case(
        "valorant_team_size",
        "VALORANT",
        "team_size",
        "competition_rules_valorant_psu_phuket_2026",
        ["VALORANT", "5 คน"],
        [
            "VALORANT แข่งทีมละกี่คน",
            "วาโลทีมละกี่คนตามกติกา",
            "VALORANT สมาชิกทีมกี่คน",
            "กติกา VALORANT ต้องมีผู้เล่นกี่คน",
            "PSU Phuket VALORANT 2026 แข่งทีมละกี่คน",
            "VALORANT ลงแข่งพร้อมกันกี่คน",
            "วาโลผู้เล่นตัวจริงกี่คน",
            "VALORANT ทีม 5 คนใช่ไหม",
            "VALORANT roster ตัวจริงกี่คน",
            "กฎแข่งวาโลจำนวนผู้เล่นต่อทีมคือเท่าไหร่",
            "VALORANT ในรายการนี้ใช้ทีมละกี่คน",
            "วาโลแข่งแบบกี่คนต่อทีม",
        ],
    ),
    case(
        "valorant_map_pool",
        "VALORANT",
        "map_pool",
        "competition_rules_valorant_psu_phuket_2026",
        ["Abyss", "Ascent", "Sunset"],
        [
            "VALORANT แผนที่ที่ใช้แข่งมีอะไรบ้าง",
            "VALORANT map pool มีอะไรบ้าง",
            "วาโลใช้ map อะไรบ้าง",
            "กติกา VALORANT ระบุแผนที่อะไรบ้าง",
            "PSU Phuket VALORANT 2026 ใช้ map ไหน",
            "VALORANT มี Abyss กับ Ascent ใน map pool ไหม",
            "วาโลแข่งบน Sunset ได้ไหม",
            "ขอรายชื่อแผนที่แข่ง VALORANT",
            "VALORANT map pool ทั้งหมดมีอะไร",
            "วาโล ban map จากแผนที่ชุดไหน",
            "VALORANT แข่งแผนที่อะไรได้บ้าง",
            "กฎวาโลเรื่อง map pool คืออะไร",
        ],
    ),
    case(
        "valorant_tactical_timeout",
        "VALORANT",
        "pause",
        "competition_rules_valorant_psu_phuket_2026",
        ["Tactical Timeout", "2 ครั้ง", "60 วินาที", "Overtime"],
        [
            "VALORANT Tactical Timeout ขอได้กี่ครั้ง",
            "วาโล timeout ได้กี่ครั้ง",
            "VALORANT เวลานอกได้กี่ครั้ง",
            "VALORANT tactical timeout ครั้งละกี่วินาที",
            "กติกา VALORANT timeout ต่อแผนที่ได้เท่าไหร่",
            "VALORANT เข้า Overtime ได้ timeout เพิ่มไหม",
            "วาโล Tactical Timeout ได้ทีมละกี่ครั้ง",
            "VALORANT ขอเวลานอก 60 วินาทีใช่ไหม",
            "VALORANT timeout ในรอบปกติได้กี่ครั้ง",
            "PSU Phuket VALORANT 2026 tactical timeout rule คืออะไร",
            "วาโลเวลานอก tactical ต่อ map ได้กี่ครั้ง",
            "VALORANT ถามเรื่อง tactical timeout ให้ตอบยังไง",
        ],
    ),
    case(
        "valorant_emergency_pause",
        "VALORANT",
        "pause",
        "competition_rules_valorant_psu_phuket_2026",
        ["Emergency", "1 ครั้ง", "10 นาที"],
        [
            "VALORANT emergency pause ได้กี่ครั้ง",
            "VALORANT technical pause รวมได้กี่นาที",
            "VALORANT pause ฉุกเฉินได้ไหม",
            "วาโลหลุดเกมขอ emergency pause ได้เท่าไหร่",
            "กติกา VALORANT หยุดฉุกเฉินได้ทีมละกี่ครั้ง",
            "VALORANT technical pause สูงสุดกี่นาที",
            "VALORANT Emergency Pause ต่อแผนที่ได้กี่ครั้ง",
            "วาโลหยุดเกมฉุกเฉินรวมกี่นาที",
            "VALORANT ถ้า hardware มีปัญหาขอ pause ยังไง",
            "VALORANT emergency pause policy คืออะไร",
            "วาโล technical pause 10 นาทีใช่ไหม",
            "VALORANT pause ฉุกเฉินตามกฎตอบว่าอะไร",
        ],
    ),
    case(
        "valorant_agent_map_restriction",
        "VALORANT",
        "character",
        "competition_rules_valorant_psu_phuket_2026",
        ["Agent", "2 สัปดาห์", "4 สัปดาห์"],
        [
            "VALORANT agent ใหม่ใช้ได้ไหม",
            "VALORANT map ใหม่ใช้ได้ไหม",
            "วาโลเอเจนท์ใหม่ใช้แข่งได้ไหม",
            "กติกา VALORANT agent ใหม่ต้องรอกี่สัปดาห์",
            "VALORANT แผนที่ใหม่ต้องรอกี่สัปดาห์ก่อนแข่ง",
            "VALORANT ใช้เอเจนท์ที่เพิ่งออกใหม่ได้ทันทีไหม",
            "วาโล map ใหม่ใช้แข่งได้เลยหรือเปล่า",
            "VALORANT new agent restriction คืออะไร",
            "VALORANT new map restriction ในกติกาคืออะไร",
            "วาโล agent ใหม่รอ 2 สัปดาห์ใช่ไหม",
            "VALORANT map ใหม่รอ 4 สัปดาห์ไหม",
            "กฎวาโลเรื่อง content ใหม่เป็นยังไง",
        ],
    ),
    case(
        "rov_team_size",
        "Arena of Valor (RoV)",
        "team_size",
        "competition_rules_rov_blueket_2025_men",
        ["5v5", "ฝ่ายละ 5 คน", "ยังไม่พบจำนวนสมาชิกทีม"],
        [
            "สมาชิกในทีม ROV ต้องมีกี่คน",
            "RoV ทีมละกี่คน",
            "ROV แข่งกี่คน",
            "สมาชิกในทีม RoV กี่คนตามกติกา",
            "กติกา RoV บอกว่าลงแข่งฝ่ายละกี่คน",
            "RoV เป็น 5v5 ใช่ไหม",
            "Blueket Games RoV ทีมละกี่คน",
            "RoV roster รวมมีกี่คนในไฟล์กติกา",
            "ROV มีตัวสำรองกี่คนในเอกสาร",
            "RoV ถามจำนวนสมาชิกทีมควรตอบยังไง",
            "Arena of Valor แข่งโหมดกี่ต่อกี่",
            "RoV ยืนยันได้ไหมว่าลงแข่งฝ่ายละ 5 คน",
        ],
        answer_type="inferred_fact",
        difficulty="hard",
    ),
    case(
        "rov_skin",
        "Arena of Valor (RoV)",
        "skin",
        "competition_rules_rov_blueket_2025_men",
        ["Default Skin"],
        [
            "RoV ใช้สกินได้ไหม",
            "ROV ใช้ skin ได้ไหม",
            "RoV ต้องใช้สกินอะไร",
            "กติกา RoV อนุญาตให้ใช้สกินไหม",
            "Blueket Games RoV ใช้ Default Skin ใช่ไหม",
            "RoV ห้ามใช้สกินอื่นไหม",
            "Arena of Valor แข่งต้องใช้ skin แบบไหน",
            "RoV ใช้สกินพิเศษได้หรือเปล่า",
            "กฎ RoV เรื่องสกินคืออะไร",
            "ROV default skin เท่านั้นไหม",
            "RoV ถ้าใช้สกินนอก default ได้ไหม",
            "RoV ในรายการนี้สกินต้องเป็นอะไร",
        ],
    ),
    case(
        "rov_late_start",
        "Arena of Valor (RoV)",
        "late_start",
        "competition_rules_rov_blueket_2025_men",
        ["15 นาที", "ปรับแพ้"],
        [
            "RoV ถ้าเริ่มแข่งช้าเกิน 15 นาทีโดนอะไร",
            "RoV มาสายเกิน 15 นาทีเป็นอะไร",
            "ROV late start 15 นาที",
            "กติกา RoV เริ่มแข่งล่าช้าเกิน 15 นาทีลงโทษยังไง",
            "Blueket Games RoV ถ้ามาสายโดนปรับแพ้ไหม",
            "RoV ถ้าทีมทำให้เริ่มช้าจะโดนอะไร",
            "RoV เริ่มช้ากี่นาทีถึงปรับแพ้",
            "Arena of Valor ล่าช้า 15 นาทีตามกฎเป็นยังไง",
            "RoV แข่งช้าเกินเวลาที่กำหนดถูกปรับแพ้ไหม",
            "ROV ถ้าเริ่ม match ไม่ทัน 15 นาทีตอบว่าอะไร",
            "กฎ RoV เรื่องมาสายคืออะไร",
            "RoV late start rule ในเอกสารคืออะไร",
        ],
    ),
    case(
        "rov_pause_disconnect",
        "Arena of Valor (RoV)",
        "pause",
        "competition_rules_rov_blueket_2025_men",
        ["5 ครั้ง", "1 นาที"],
        [
            "RoV pause ได้กี่ครั้ง",
            "RoV หลุดเกมหยุดได้ไหม",
            "RoV disconnect ทำยังไง",
            "กติกา RoV หยุดเกมได้ทีมละกี่ครั้ง",
            "RoV pause ครั้งละกี่นาที",
            "Blueket Games RoV ถ้าเกมหลุดขอหยุดได้เท่าไหร่",
            "RoV แต่ละทีมมีสิทธิ์หยุดเกมกี่ครั้ง",
            "Arena of Valor pause ได้สูงสุดกี่ครั้ง",
            "RoV หยุดเกมได้ 5 ครั้งใช่ไหม",
            "ROV pause 1 นาทีต่อครั้งใช่หรือเปล่า",
            "RoV disconnect แล้วกลับมาเล่นต่อเมื่อไหร่",
            "กฎ RoV เรื่อง pause/disconnect คืออะไร",
        ],
    ),
    case(
        "rov_rematch",
        "Arena of Valor (RoV)",
        "rematch",
        "competition_rules_rov_blueket_2025_men",
        ["First Blood", "2 นาที"],
        [
            "RoV ขอเริ่มใหม่ได้ไหม",
            "RoV ก่อน first blood remake ได้ไหม",
            "RoV แข่งใหม่ได้ตอนไหน",
            "กติกา RoV rematch ทำได้เมื่อไหร่",
            "RoV ขอแข่งใหม่ก่อน 2 นาทีได้ไหม",
            "Blueket Games RoV ถ้าเกิด First Blood แล้ว remake ได้ไหม",
            "Arena of Valor เริ่มใหม่ได้ก่อน First Blood ใช่ไหม",
            "RoV ถ้าเกิน 2 นาทีแล้วขอแข่งใหม่ได้ไหม",
            "RoV ต้องให้ฝ่ายตรงข้ามยินยอมเมื่อไหร่",
            "ROV rematch rule ตามเอกสารคืออะไร",
            "RoV remake ก่อน First Blood และก่อน 2 นาทีใช่ไหม",
            "กฎ RoV เรื่องขอแข่งใหม่ตอบยังไง",
        ],
    ),
    case(
        "rov_device",
        "Arena of Valor (RoV)",
        "equipment",
        "competition_rules_rov_blueket_2025_men",
        ["โทรศัพท์มือถือ", "ไม่อนุญาต", "Tablet", "iPad"],
        [
            "RoV ใช้อุปกรณ์อะไรแข่ง",
            "RoV ใช้ iPad แข่งได้ไหม",
            "RoV ใช้ tablet ได้ไหม",
            "RoV แข่งด้วยเครื่องอะไร",
            "กติกา RoV ต้องใช้มือถือไหม",
            "Blueket Games RoV อนุญาต iPad หรือเปล่า",
            "Arena of Valor แข่งด้วยโทรศัพท์มือถือเท่านั้นไหม",
            "RoV ใช้ Tablet ในการแข่งขันได้หรือไม่",
            "ROV device rule คืออะไร",
            "RoV อุปกรณ์ที่ใช้แข่งกำหนดยังไง",
            "RoV ถ้าจะใช้ iPad ต้องได้ไหมตามกฎ",
            "กฎ RoV เรื่องอุปกรณ์แข่งคืออะไร",
        ],
    ),
    case(
        "tekken_format",
        "Tekken 8",
        "format",
        "competition_rules_tekken8_psu_esports",
        ["1v1", "PlayStation 5", "FT2", "60 วินาที"],
        [
            "Tekken 8 เล่นแบบไหน",
            "Tekken 8 รูปแบบการแข่งขัน",
            "Tekken 8 แข่งกี่ต่อกี่",
            "กติกา Tekken 8 ใช้ format อะไร",
            "Tekken 8 เป็น 1v1 ใช่ไหม",
            "Tekken 8 FT2 คือรูปแบบแข่งใช่ไหม",
            "Tekken 8 แข่งบน PS5 และเวลา 60 วินาทีไหม",
            "PSU Esports Tekken 8 แข่งแบบ offline หรือเปล่า",
            "Tekken 8 รอบหนึ่งตั้งเวลากี่วินาที",
            "Tekken 8 ใช้ Round 3 ไหม",
            "Tekken 8 format ในเอกสารคืออะไร",
            "Tekken 8 กติกาการแข่งขันสรุปยังไง",
        ],
    ),
    case(
        "tekken_equipment",
        "Tekken 8",
        "equipment",
        "competition_rules_tekken8_psu_esports",
        ["PlayStation 5"],
        [
            "Tekken 8 ใช้เครื่องอะไรแข่ง",
            "Tekken 8 แข่งบนอะไร",
            "Tekken 8 platform อะไร",
            "กติกา Tekken 8 ระบุเครื่องแข่งว่าอะไร",
            "Tekken 8 ใช้ PS5 แข่งใช่ไหม",
            "PSU Esports Tekken 8 ใช้ PlayStation 5 หรือเปล่า",
            "Tekken 8 อุปกรณ์หลักที่ใช้แข่งคืออะไร",
            "Tekken 8 แข่งด้วยเครื่องเกมอะไร",
            "Tekken 8 platform ตามเอกสารคืออะไร",
            "Tekken 8 ใช้ console อะไรในการแข่ง",
            "Tekken 8 ต้องเล่นบน PlayStation 5 ไหม",
            "กฎ Tekken 8 เรื่อง platform คืออะไร",
        ],
    ),
    case(
        "tekken_character",
        "Tekken 8",
        "character",
        "competition_rules_tekken8_psu_esports",
        ["ยกเว้นตัวละคร DLC", "Customization"],
        [
            "Tekken 8 ใช้ DLC character ได้ไหม",
            "Tekken 8 ใช้ตัวละคร DLC ได้ไหม",
            "Tekken 8 เลือกตัวละครอะไรได้บ้าง",
            "กติกา Tekken 8 ห้าม DLC ใช่ไหม",
            "Tekken 8 ใช้ customization ได้ไหม",
            "Tekken 8 ใช้ชุดแต่งตัวละครได้หรือเปล่า",
            "PSU Esports Tekken 8 ตัวละคร DLC แข่งได้ไหม",
            "Tekken 8 ใช้ skin custom ได้ไหม",
            "Tekken 8 character rule คืออะไร",
            "Tekken 8 เลือกได้ทุกตัวยกเว้น DLC ใช่ไหม",
            "Tekken 8 ห้าม customization ตามกฎหรือไม่",
            "กฎ Tekken 8 เรื่องตัวละครและสกินคืออะไร",
        ],
    ),
    case(
        "tekken_pause",
        "Tekken 8",
        "pause",
        "competition_rules_tekken8_psu_esports",
        ["ไม่อนุญาต", "Pause", "แพ้ 1 Round"],
        [
            "Tekken 8 pause ได้ไหม",
            "Tekken 8 หยุดเกมได้ไหม",
            "Tekken 8 กด pause โดนอะไร",
            "กติกา Tekken 8 ถ้ากด pause หลังเริ่มเกมเป็นยังไง",
            "Tekken 8 ตั้งใจกดหยุดเกมโดนปรับแพ้ไหม",
            "Tekken 8 pause แล้วแพ้ 1 Round ใช่ไหม",
            "PSU Esports Tekken 8 ห้าม pause หรือเปล่า",
            "Tekken 8 หยุดเกมได้เฉพาะกรณีไหน",
            "Tekken 8 ถ้าทั้งสองฝ่ายยินยอม pause ได้ไหม",
            "Tekken 8 pause penalty คืออะไร",
            "Tekken 8 กด pause ระหว่างแข่งลงโทษยังไง",
            "กฎ Tekken 8 เรื่อง pause ตอบว่าอะไร",
        ],
    ),
]


def build_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    index = 1
    for item in CASES:
        for variant_index, question in enumerate(item["questions"], 1):
            rows.append({
                "id": f"competition_v1_{index:03d}",
                "category": "competition_rules",
                "game": item["game"],
                "intent": item["intent"],
                "question": question,
                "expected_keywords": item["expected_keywords"],
                "expected_source_keywords": [item["source_id"]],
                "answer_type": item["answer_type"],
                "difficulty": item["difficulty"] if variant_index <= 8 else "hard",
                "variant_type": f"competition_{item['intent']}",
                "source_fact_key": item["key"],
                "expected_mode_prefix": "pipeline:competition_fact_card",
            })
            index += 1
    return rows


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    rows = build_rows()
    with OUTPUT_PATH.open("w", encoding="utf-8", newline="\n") as file:
        for row in rows:
            file.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"Wrote {len(rows)} rows")
    print(OUTPUT_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
